name: Create a pull request

on:
  push:
    branches:
      - token-studio

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: 'main'
          pr_title: 'Figma Tokens Update'
          pr_body: '🍥 Design Tokens were updated in Figma!'
          github_token: ${{ secrets.PULL_REQUEST_TOKEN }}